apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: devops-project
  template:
    metadata:
      labels:
        tier: backend
        app: devops-project
    spec:
      containers:
      - name: backend
        image: tamkeenzarah/python-backend:devops-project
        ports:
        - containerPort: 8080
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    tier: backend
    app: devops-project
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
