
FROM node:10-alpine

LABEL name="Devops Project" \   
     maintainer="TamkeenZarah <tamkeenzarah@gmail.com>" \
     summary="Devops Project"


WORKDIR /app

EXPOSE 8080

COPY package*.json ./

RUN npm install

RUN apk add curl 

COPY server.js ./

CMD [ "npm", "start" ]


