
pipeline {
  agent any
  environment {
		registryCredential = 'dockerhub' 
	}
  stages {
    stage('Build') {
			steps {
				dir('Frontend-Project-Pipline'){
					sh 'docker build -t kahootali/test-node-app .'
				}
			} 
		}
    stage('Test') {
      steps {
			dir('Frontend-Project-Pipline'){
				sh 'docker container run --rm -p 8001:8080 --name node -d kahootali/test-node-app' 
				sh 'sleep 5'
				sh 'curl -I http://localhost:8001'
			}
		} 
	}
    stage('Publish') {
		steps{
			script {
				docker.withRegistry( '', registryCredential ) {
					sh 'docker push tamkeenzarah/project-node-app:latest'
				} 
			}
		} 
	}
	stage('Deploy') {
		steps {
			dir('Frontend-Project-Pipline'){
				sh 'docker compose up --build' 
			}
		}
	}
  }
}
