
pipeline {
    agent {
        docker { 
            image 'node:16.13.1-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
        stage('build'){
            node {
                    checkout scm

                    def customImage = docker.build("my-image:${env.BUILD_ID}")

}
        
        }
    }
}
